version: "3.3"
services:
#  api:
#    build: .
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#    container_name: "fd-content-recommendation-api"
#    volumes:
#      - ~/.aws/:/root/.aws:ro
  db:
    image: postgres
    container_name: fastapi-db-container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
     - ${POSTGRES_PORT_HOST_MACHINE}:5432