version: "3.3"
services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    container_name: "fastapi-backend-api"
#    volumes:
#      - ~/.aws/:/root/.aws:ro
  db:
    image: postgres
    container_name: fastapi-db-container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
     - ${DB_PORT}:5432